# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a35tcpg236-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/student/Desktop/Lab6VP/mips/mips.cache/wt [current_project]
set_property parent.project_path C:/Users/student/Desktop/Lab6VP/mips/mips.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/student/Desktop/Lab6VP/mips/mips.srcs/sources_1/new/ProcMem_definitions.vhd
  C:/Users/student/Desktop/Lab6VP/mips/mips.srcs/sources_1/new/regfile.vhd
  C:/Users/student/Desktop/Lab6VP/mips/mips.srcs/sources_1/new/phaseGenerator.vhd
  C:/Users/student/Desktop/Lab6VP/mips/mips.srcs/sources_1/new/pc.vhd
  C:/Users/student/Desktop/Lab6VP/mips/mips.srcs/sources_1/new/instreg.vhd
  C:/Users/student/Desktop/Lab6VP/mips/mips.srcs/sources_1/new/controlUnit.vhd
  C:/Users/student/Desktop/Lab6VP/mips/mips.srcs/sources_1/new/alu.vhd
  C:/Users/student/Desktop/Lab6VP/mips/mips.srcs/sources_1/new/main.vhd
}
catch { write_hwdef -file main.hwdef }
synth_design -top main -part xc7a35tcpg236-1
write_checkpoint -noxdef main.dcp
catch { report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb }
